# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 423)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 691, 71))
        self.textEdit.setObjectName("textEdit")
        self.analyzeButton = QtWidgets.QPushButton(self.centralwidget)
        self.analyzeButton.setGeometry(QtCore.QRect(0, 80, 281, 81))
        self.analyzeButton.setObjectName("analyzeButton")
        self.semanticButton = QtWidgets.QPushButton(self.centralwidget)
        self.semanticButton.setGeometry(QtCore.QRect(320, 80, 371, 81))
        self.semanticButton.setObjectName("semanticButton")
        self.errorsLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorsLabel.setGeometry(QtCore.QRect(0, 200, 291, 100))
        self.errorsLabel.setWordWrap(True)
        self.errorsLabel.setObjectName("errorsLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 210, 125, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 210, 91, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 691, 16))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(290, 80, 16, 301))
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 170, 691, 16))
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.identifiersList = QtWidgets.QListWidget(self.centralwidget)
        self.identifiersList.setGeometry(QtCore.QRect(320, 240, 171, 141))
        self.identifiersList.setObjectName("identifiersList")
        self.constantsList = QtWidgets.QListWidget(self.centralwidget)
        self.constantsList.setGeometry(QtCore.QRect(500, 240, 181, 141))
        self.constantsList.setObjectName("constantsList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализатор условного оператора"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "IF ... THEN ... ELSE ...;"))
        self.analyzeButton.setText(_translate("MainWindow", "Проанализировать"))
        self.semanticButton.setText(_translate("MainWindow", "Вывести семантику"))
        self.errorsLabel.setText(_translate("MainWindow", "Ошибки"))
        self.label.setText(_translate("MainWindow", "Идентификаторы"))
        self.label_2.setText(_translate("MainWindow", "Константы"))
